Internal Server Error: /hotels/hotel/38/room/624/
Traceback (most recent call last):
  File "C:\Users\HP-\Desktop\projects\pluto\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP-\Desktop\projects\pluto\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP-\Desktop\projects\pluto\hotel\views.py", line 235, in roomDetails
    callbackUrl = f"https://plutobooking.com/callback/{invoiceNumber}"
                                                       ^^^^^^^^^^^^^
NameError: name 'invoiceNumber' is not defined
"POST /hotels/hotel/38/room/624/ HTTP/1.1" 500 145
